services:
  backend:
    build: .
    container_name: gorace-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./app.db:/app/app.db

volumes: {}
